### ISSUE TITLE
Make a live iso

### ISSUE THREAD

**Issue by Deshapria** [brontosaurusrex/postbang#3]
By finding your Brontowiki very good, all I got was banned from that forum. I am not sure, any one would ever join that forum for some time. Some pretty unhappy guys are there now. Anyway, I found your Brontowiki excellent, so maybe you'd consider a live iso, or a install iso from your ideas. Would be happy, if you create a live iso. Desh is shortform for Deshapria.

**Comment by brontosaurusrex** [comment]
No such plans at the moment, but of course you are free to roll out an iso based on the code/ideas here.
